"""Write signal-theme/signal_font.py: the Figtree typeface (Latin subset, variable 400-800) as base64.

The theme embeds the font in its CSS so apps make no request to Google Fonts. Keeping it in a .py module means
it ships with every app package without extra package-data. Re-run after replacing assets/fonts/*:

    python signal-theme/tools/build_font_module.py
"""

from __future__ import annotations

import base64
from pathlib import Path
import textwrap

THEME = Path(__file__).resolve().parents[1]
FONT = THEME / "assets" / "fonts" / "figtree-latin.woff2"
LICENSE = THEME / "assets" / "fonts" / "OFL.txt"


def main() -> None:
    data = base64.b64encode(FONT.read_bytes()).decode("ascii")
    lines = textwrap.wrap(data, 116)
    notice = LICENSE.read_text(encoding="utf-8").strip().replace('"""', "'''")
    body = "\n".join(f'    "{line}"' for line in lines)
    text = (
        '"""Figtree typeface, Latin subset (U+0000-00FF and common punctuation), variable weight 400-800, as woff2.\n\n'
        "Generated by signal-theme/tools/build_font_module.py from Google Fonts' Figtree. Embedded so Signal apps load\n"
        "no web font from a third party. Licence (it must travel with the font):\n\n"
        f"{notice}\n"
        '"""\n\n'
        f"FIGTREE_WOFF2_B64 = (\n{body}\n)\n"
    )
    (THEME / "signal_font.py").write_text(text, encoding="utf-8")
    print(f"wrote signal_font.py ({len(data)} base64 chars)")


if __name__ == "__main__":
    main()
