# Repo descriptions, topics and social previews. Needs the GitHub CLI: https://cli.github.com (gh auth login).
# Run from PowerShell. Safe to re-run. Social previews must be uploaded by hand (see REPO_SETTINGS.md).
# Generated from apps.yaml by scripts/sync_suite.py.

gh repo edit UlrikErlingsen/signal-hub --description "Signal Hub: every Signal marketing-evidence tool behind one link. Open-source, local-first." --homepage "https://ulrikerlingsen.com" --add-topic signal-suite --add-topic streamlit --add-topic local-first --add-topic marketing-analytics --add-topic portfolio
gh repo edit UlrikErlingsen/brand-tracking --description "Track Signal: is the brand moving, or is the tracker just noisy? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-brand --add-topic streamlit --add-topic local-first --add-topic brand-tracking --add-topic survey-analysis
gh repo edit UlrikErlingsen/brand-positioning --description "Position Signal: where do brands sit relative to competitors? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-brand --add-topic streamlit --add-topic local-first --add-topic perceptual-mapping --add-topic pca
gh repo edit UlrikErlingsen/b2b-prospecting --description "Prospect Signal: which Norwegian companies fit your ideal customer, and which first? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-market --add-topic streamlit --add-topic local-first --add-topic b2b --add-topic brreg
gh repo edit UlrikErlingsen/media-listening --description "Listen Signal: who is talking about the brand in Norwegian media, and in what tone? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-market --add-topic streamlit --add-topic local-first --add-topic media-monitoring --add-topic sentiment-analysis
gh repo edit UlrikErlingsen/influencer-campaigns --description "Influence Signal: which creators delivered, and was every post labelled properly? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-market --add-topic streamlit --add-topic local-first --add-topic influencer-marketing --add-topic norway
gh repo edit UlrikErlingsen/marketing-calendar --description "Season Signal: what does the Norwegian marketing year look like, worked backwards? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-market --add-topic streamlit --add-topic local-first --add-topic marketing-calendar --add-topic norway
gh repo edit UlrikErlingsen/adoption-forecasting --description "Adopt Signal: when will a new product be adopted? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-market --add-topic streamlit --add-topic local-first --add-topic bass-diffusion --add-topic forecasting
gh repo edit UlrikErlingsen/competitor-analysis --description "Rival Signal: which rivals matter, and how could they respond? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-market --add-topic streamlit --add-topic local-first --add-topic competitive-analysis --add-topic competitive-intelligence
gh repo edit UlrikErlingsen/location-catchment-analysis --description "Reach Signal: where could a new location reach, and how would it share demand with existing sites? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-market --add-topic streamlit --add-topic local-first --add-topic location-analytics --add-topic huff-model
gh repo edit UlrikErlingsen/customer-value-analytics --description "Worth Signal: what are customers and relationships worth? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-customer --add-topic streamlit --add-topic local-first --add-topic clv --add-topic rfm
gh repo edit UlrikErlingsen/customer-segmentation --description "Segment Signal: do customers form stable, useful groups? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-customer --add-topic streamlit --add-topic local-first --add-topic segmentation --add-topic clustering
gh repo edit UlrikErlingsen/journey-path-analysis --description "Trace Signal: how do logged customer journeys actually unfold? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-customer --add-topic streamlit --add-topic local-first --add-topic customer-journey --add-topic markov-chain
gh repo edit UlrikErlingsen/service-blueprinting --description "Blueprint Signal: how is the customer experience actually delivered, and where do the handoffs fail? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-customer --add-topic streamlit --add-topic local-first --add-topic service-design --add-topic service-blueprint
gh repo edit UlrikErlingsen/recommender-evaluation --description "Recommend Signal: which recommendation policy should be tested live? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-customer --add-topic streamlit --add-topic local-first --add-topic recommender-systems --add-topic offline-evaluation
gh repo edit UlrikErlingsen/conjoint-analysis --description "Choice Signal: how do product attributes drive choice? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-research --add-topic streamlit --add-topic local-first --add-topic conjoint-analysis --add-topic market-research
gh repo edit UlrikErlingsen/survey-driver-analysis --description "Driver Signal: which measured experiences move with satisfaction? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-research --add-topic streamlit --add-topic local-first --add-topic driver-analysis --add-topic survey-analysis
gh repo edit UlrikErlingsen/measurement-validation --description "Measure Signal: does a multi-item score have a defensible structure? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-research --add-topic streamlit --add-topic local-first --add-topic psychometrics --add-topic factor-analysis
gh repo edit UlrikErlingsen/open-text-analysis --description "Text Signal: what recurring patterns appear in open-ended responses? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-research --add-topic streamlit --add-topic local-first --add-topic text-analysis --add-topic nmf
gh repo edit UlrikErlingsen/pricing-analysis --description "Tag Signal: what price range is supported, and how does profit move? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-research --add-topic streamlit --add-topic local-first --add-topic pricing --add-topic price-elasticity
gh repo edit UlrikErlingsen/research-prioritization --description "Learn Signal: which uncertainty is worth paying to research before you decide? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-research --add-topic streamlit --add-topic local-first --add-topic value-of-information --add-topic decision-analysis
gh repo edit UlrikErlingsen/experiment-analysis --description "Experiment Signal: did the treatment cause a practically meaningful change? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-decide --add-topic streamlit --add-topic local-first --add-topic ab-testing --add-topic experimentation
gh repo edit UlrikErlingsen/launch-decision-gate --description "Gate Signal: does a concept deserve the next investment? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-decide --add-topic streamlit --add-topic local-first --add-topic new-product-development --add-topic stage-gate
gh repo edit UlrikErlingsen/cannibalization-analysis --description "Shift Signal: does a launch grow the portfolio, or move existing demand around? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-decide --add-topic streamlit --add-topic local-first --add-topic cannibalization --add-topic difference-in-differences
gh repo edit UlrikErlingsen/marketing-mix-allocation --description "Alloc Signal: where should the next marketing budget go? Open-source, local-first Streamlit app." --homepage "https://github.com/UlrikErlingsen/signal-hub" --add-topic signal-suite --add-topic signal-decide --add-topic streamlit --add-topic local-first --add-topic marketing-mix --add-topic budget-optimization
